
[functions.fetch-price]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-price/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-price/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-price/*.html" ]

# Harden Auth password checks (HaveIBeenPwned leak protection)
[auth.hibp]
enabled = true

[functions.fre-price-snapshot]
enabled = true
verify_jwt = true
import_map = "./functions/fre-price-snapshot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fre-price-snapshot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fre-price-snapshot/*.html" ]
